import { PATHS } from "../paths";
import type { CreateInstallModule, ThemeTokens, Variant } from "../types";
import { installFile, writeText } from "../utils";

function buildSuperfileTheme(v: Variant): string {
	const primary = "#AFAF00";
	const secondary = "#AFAF00";
	const border = "#3A3A3C";
	const activeBorder = "#77770D";

	return `# Generated by packages/theming/create/apps/superfile.ts
code_syntax_highlight = "gruvbox"

full_screen_fg = "${v.foreground}"
full_screen_bg = "${v.background}"

gradient_color = ["${primary}", "${secondary}"]
directory_icon_color = "${secondary}"

file_panel_fg = "${v.foreground}"
file_panel_bg = "${v.background}"
file_panel_border = "${border}"
file_panel_border_active = "${activeBorder}"
file_panel_top_directory_icon = "${secondary}"
file_panel_top_path = "${primary}"
file_panel_item_selected_fg = "${v.selectionForeground}"
file_panel_item_selected_bg = "${v.selectionBackground}"

footer_fg = "${v.foreground}"
footer_bg = "${v.background}"
footer_border = "${border}"
footer_border_active = "${activeBorder}"

sidebar_fg = "${v.foreground}"
sidebar_bg = "${v.background}"
sidebar_title = "${primary}"
sidebar_border = "${border}"
sidebar_border_active = "${activeBorder}"
sidebar_item_selected_fg = "${v.selectionForeground}"
sidebar_item_selected_bg = "${v.selectionBackground}"
sidebar_divider = "${v.foregroundMuted}"

modal_fg = "${v.foreground}"
modal_bg = "${v.backgroundPanel}"
modal_border_active = "${activeBorder}"
modal_cancel_fg = "${v.background}"
modal_cancel_bg = "${v.error}"
modal_confirm_fg = "${v.background}"
modal_confirm_bg = "${secondary}"

help_menu_hotkey = "${v.accent}"
help_menu_title = "${primary}"

cursor = "${v.cursor}"
correct = "${v.success}"
error = "${v.error}"
hint = "${v.info}"
cancel = "${v.warning}"
`;
}

export const superfileApp: CreateInstallModule = {
	appName: "superfile",
	async create(tokens: ThemeTokens) {
		await writeText(
			PATHS.output.superfile.theme,
			buildSuperfileTheme(tokens.variants.dark),
		);
		return [PATHS.output.superfile.theme];
	},
	async install() {
		await installFile(
			PATHS.output.superfile.theme,
			PATHS.install.superfile.theme,
		);
		return [PATHS.install.superfile.theme];
	},
};
